import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import data from "../public/faq.json";
import Header from "../components/Header";
import Card from "../components/Card";
import Testimony from "../components/TestimonyCard";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <div className="body">
      <Head>
        <title>Manage Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        ></link>
      </Head>

      <main className={styles.main}>
        <div className="container">
          <Header />
          <div className={styles.intro_board}>
            <div className={styles.motto_wrapper}>
              <h1 className={styles.motto}>
                Bring everyone together to build better products.{" "}
              </h1>

              <div className={styles.sub_motto}>
                <p>
                  Manage makes it simple for software teams to plan day-to-day
                  tasks while keeping the larger team goals in view.
                </p>
              </div>

              <div className={styles.btnwrapper}>
                <Link href="/get-Started">
                  <a className="getstarted_btn">Get Started</a>
                </Link>
              </div>
            </div>

            <div className={styles.ill}>
              <Image
                src="/images/illustration-intro.svg"
                width={400}
                height={400}
                alt="illustration-intro"
              />
            </div>
          </div>

          <div className={styles.b2}>
            <div className={styles.one}>
              <h2>What’s different about Manage?</h2>

              <p>
                Manage provides all the functionality your team needs, without
                the complexity. Our software is tailor-made for modern digital
                product teams.
              </p>
            </div>

            <div className="two">
              <Card />
            </div>
          </div>
        </div>

        <div>
          <h1 className={styles.tes_title_label}>What they’ve said</h1>
          <Testimony />
        </div>

        <Footer />
      </main>
    </div>
  );
}
